name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: resu
          POSTGRES_DB: shopper_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create .env file for PostgreSQL
      run: |
        cat << EOF > .env
        NODE_ENV=test
        PORT=3000
        HOST=localhost
        SESSION_SECRET=qwertyuiop
        DB_TYPE=postgres
        DB_HOST=localhost
        DB_PORT=5432
        DB_NAME=shopper_db
        DB_USER=user
        DB_PASSWORD=resu
        EOF

    - name: Run tests
      run: npm test